### ISSUE TITLE
Nothing appering when trying to test

### ISSUE THREAD

**Issue by MTRNord** [davidferguson/pibakery-blocks#7] opened 2016-09-07 16:04 UTC
I used as base the lamp dir for my NGINX Builder but when I try to drag and drop my folder into the pibakery program nothing appears. No Success and no error. Code is here: https://github.com/MTRNord/pibakery-blocks/tree/10f3cfcb089c7c24b544cd5d20ba5f6e113c1b2e/nginx

**Comment by davidferguson** [comment] 2016-09-07 17:06
Apologies, there was an error in my docs, the "type" and "category" should be set to "software", rather than "program".

Thanks for pointing this out - I've now fixed the docs.

**Comment by MTRNord** [comment] 2016-09-07 17:18
Still it doesn't want to import it. Same to all directories. I use Windows 7 as system  and an completly fresh Version. Not even any Output about it in the Log (using the flag --enable-logging)

**Comment by MTRNord** [comment] 2016-09-07 17:20
If I manually put it into "C:\Program Files (x86)\PiBakery\resources\app\pibakery-blocks" and add it to the "info.json" it works. Drag and Drop into Workspace does nothing

**Comment by davidferguson** [comment] 2016-09-07 17:29
That's odd, I got it to work for me. If you do CTRL-SHIFT-I, you'll see the developer inspector, if you go into the "Console" tab, are there any errors?

And can you post the contents of your `nginx.json` file?

**Comment by MTRNord** [comment] 2016-09-07 17:30
Code of nginx.json

```
{
	"name": "nginx",
	"text": "Builds NGINX with http2, ssl and ipv6 support\\nRequires internet connection",
	"script": "nginxBuild.sh",
	"args": [],
	"network": true,
	"continue": true,
	"type": "software",
	"category":"software",
	"shortDescription":"Install a web server on your Raspberry Pi. Requires internet connection.",
	"longDescription":"NGINX is a web server for more experienced users to run their websites. This builds NGINX from source."
}
```

At the Dev Console I will have a look

**Comment by MTRNord** [comment] 2016-09-07 17:32
Dev Console gives no special errors about the Drag and Drop action. Only the expected missing Configs on my USB Devices are in the Dev Console.

**Comment by davidferguson** [comment] 2016-09-07 17:34
Just tried your nginx.json, and it did work for me (image attached). I'm going to reinstall my copy of PiBakery - just in case I'm using a different version than the one on the downloads page.

**Comment by MTRNord** [comment] 2016-09-07 17:46
I think I got an trace. I added an "console.log(error) at Line 2381 in the pibakery.js file and got: "Error: ENOENT: no such file or directory, stat 'C:\Program Files (x86)\PiBakery\resources\app\nginx\C:\Program Files (x86)\PiBakery\resources\app\nginx.json'(…)" when dropping

**Comment by davidferguson** [comment] 2016-09-07 17:47
I'll have to look into that a little bit later - as I'm on a Mac right now and therefore can't reproduce that error.

**Comment by MTRNord** [comment] 2016-09-07 17:48
ok maybe I found the error for my self (I also work with electron ^^). If I got an fix I will give you an pull request

**Comment by MTRNord** [comment] 2016-09-07 17:53
Error seems like that win does use an backslash in it's paths. I write an exception for windows therefore

**Comment by MTRNord** [comment] 2016-09-07 18:47
I think this issue can be closed because I added an pull request with the fix

**Comment by davidferguson** [comment] 2016-09-07 19:16
Just tested it and that worked perfectly - thanks.

I'm building a new Windows version right now, and as soon as that's done I'll upload it. Uploading will take a while on my abysmal connection, but hopefully this can be released tonight.

**Comment by davidferguson** [comment] 2016-09-07 20:55
Hmm, I've now tested on Windows 8 and it seems there's another bug, but this time it's actually in Windows. It seems that on some versions of Windows, drag-drop isn't allowed with programs that run as Administrator.
I may add a shortcut in that opens a selection pane for users to choose a folder.

**Comment by davidferguson** [comment] 2016-09-07 21:19
I've now added a shortcut to open a dialog to choose a folder, which gets round the drag-drop not working on some version of Windows. PiBakery is being re-packaged and I'll upload it after that.

**Comment by davidferguson** [comment] 2016-09-08 17:18
The latest version of PiBakery (0.2.4) fixes this issue. If you are finding that you are not able to drag-drop your block folder into PiBakery, the keybaord shortcut CTRL (CMD on Mac) + Shift + "+" (plus key) can be used to open a dialog to choose your block folder.

**Closed by davidferguson** 2016-09-08 17:18 UTC
Labels: bug

**Comment by MTRNord** [comment] 2016-09-08 17:28
I already working on another optimation to better resolv the path error. :) I think path.join() could be better than path.normalize() I am testing it on windows just now. If my Idea works you get another pull request. And tanks for the fast and helpfull Help!!
